version: "3.9"

services:
  db:
    image: postgres:16
    container_name: containerPostgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: CRUD-Game-List
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d CRUD-Game-List || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 20
      start_period: 5s

  api:
    build:
      context: ./CRUD-Game-List
      dockerfile: Dockerfile
    container_name: crudGameListApi
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://0.0.0.0:8080  
      ConnectionStrings__PostgreConnection: "Host=db;Port=5432;Username=postgres;Password=admin123;Database=CRUD-Game-List"
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy

volumes:
  pgdata:
